language: php

php: 
  - 5.3
  - 5.4
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --dev --no-interaction

script:
  - phpunit

after_script:
  - php vendor/bin/coveralls -v